
USE ROLE ACCOUNTADMIN;

CREATE ROLE GITEA_SERVICE_ROLE;
GRANT CREATE DATABASE ON ACCOUNT TO ROLE GITEA_SERVICE_ROLE;
GRANT CREATE WAREHOUSE ON ACCOUNT TO ROLE GITEA_SERVICE_ROLE;
GRANT CREATE COMPUTE POOL ON ACCOUNT TO ROLE GITEA_SERVICE_ROLE;
GRANT CREATE INTEGRATION ON ACCOUNT TO ROLE GITEA_SERVICE_ROLE;
GRANT MONITOR USAGE ON ACCOUNT TO  ROLE  GITEA_SERVICE_ROLE;
GRANT BIND SERVICE ENDPOINT ON ACCOUNT TO ROLE GITEA_SERVICE_ROLE;
GRANT IMPORTED PRIVILEGES ON DATABASE SNOWFLAKE TO ROLE GITEA_SERVICE_ROLE;

CREATE USER GITEA_SERVICE_USER;

GRANT ROLE GITEA_SERVICE_ROLE TO USER GITEA_SERVICE_USER;

GRANT ROLE GITEA_SERVICE_ROLE TO ROLE SYSADMIN;

USE ROLE GITEA_SERVICE_ROLE;


CREATE OR REPLACE DATABASE GITEA_DB;
USE DATABASE GITEA_DB;

CREATE OR REPLACE WAREHOUSE GITEA_WH
WAREHOUSE_SIZE = XSMALL
AUTO_SUSPEND = 60
AUTO_RESUME = TRUE;

--Gitea recommends 2CPU cores, and XS gives us only one, additional we are running POSTGRES
--so it makes senses to have A S instance
CREATE COMPUTE POOL IF NOT EXISTS GITEA_COMPUTE_POOL
MIN_NODES = 1
MAX_NODES = 1
INSTANCE_FAMILY = CPU_X64_S;

--it suspends when you don't use it after a certain period of time.
ALTER COMPUTE POOL GITEA_COMPUTE_POOL SET AUTO_SUSPEND_SECS = 300;





--CREATE THE SERVICE USER 


--





