

--STOP! BEFORE YOU PROCEED MAKE SURE YOU UPLOAD YOUR YAML AND YOU MAKE AND UPLOAD THE IMAGES

USE ROLE GITEA_SERVICE_ROLE;
USE DATABASE GITEA_DB;

CREATE SERVICE GITEA_DB.PUBLIC.GITEA_SERVICE
IN COMPUTE POOL GITEA_COMPUTE_POOL
FROM @specs
specification_file='gitea.yaml'
EXTERNAL_ACCESS_INTEGRATIONS = (GITEA_EXTERNAL_ACCESS);